# Generated by Django 4.1.7 on 2023-02-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_roommessage_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roommessage',
            options={'ordering': ('created_at',)},
        ),
    ]
